# Generated by Django 4.0.6 on 2022-07-16 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TechinalWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='il',
        ),
        migrations.RemoveField(
            model_name='details',
            name='sp',
        ),
        migrations.AddField(
            model_name='allcources',
            name='startedfrom',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Started From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='courcetype',
            field=models.CharField(default=datetime.datetime(2022, 7, 16, 1, 5, 4, 933428, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
