# Generated by Django 4.0.6 on 2022-07-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechinalWeb', '0003_alter_allcources_startedfrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('stu_id', models.IntegerField()),
            ],
        ),
    ]
