# Generated by Django 4.0.6 on 2022-07-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechinalWeb', '0004_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='coursename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
