# Generated by Django 4.0.4 on 2022-04-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=64)),
                ('eno', models.IntegerField()),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=64)),
            ],
        ),
    ]
